docker_image: "{{ lookup('env', 'PROD_DOCKER_USERNAME') }}/dotnet-api:latest"
docker_container_name: dotnet-api
docker_ports:
  - "5000:5000"
aspnetcore_environment: Production
aspnetcore_urls: "http://+:5000"