- hosts: droplet
  become: yes
  tasks:
    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true
      become: true

    - name: Add Docker GPG key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      become: true

    - name: Add Docker APT repository
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          state: present
          filename: docker
          update_cache: true
      become: true

    - name: Ensure Docker CE is installed (latest version)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: latest
      become: true

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      become: true
    
    - name: Pull API Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: true
    
    - name: docker compose down
      ansible.builtin.command: docker-compose down
      args:
        chdir: /root/renter-score

    - name: docker compose up
      ansible.builtin.command: docker-compose up -d --build
      args:
        chdir: /root/renter-score


      
