- hosts: droplet
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      become: true

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      become: true
    
    - name: Pull API Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: true

    - name: Run API container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports: "{{ docker_ports }}"
        env:
          ASPNETCORE_ENVIRONMENT: "{{ aspnetcore_environment }}"
          HTTP_PORTS: "{{ http_ports }}"
          CONNECTIONSTRING_DEFAULT: "{{ connectionstring_default }}"