name: Deploy - Development

on:
  push:
    branches:
      - develop

jobs:
  deploy-to-development-server: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Steven's Docker Hub
      run: echo "${{ secrets.STEVEN_DOCKER_READ_WRITE_TOKEN }}" | docker login -u "***REMOVED***" --password-stdin
    
    - name: Build Docker image and push to Steven's Docker Hub
      run: |
        docker build -t renter-score-api-v2:latest .
        docker tag renter-score-api-v2:latest ***REMOVED***/renter-score-api-v2:latest
        docker push ***REMOVED***/renter-score-api-v2:latest
      working-directory: RenterScoreAPIv2
    
    - name: Log in to Tun Tun's Docker Hub
      run: echo "${{ secrets.TUNTUN_DOCKER_READ_WRITE_TOKEN }}" | docker login -u "***REMOVED***" --password-stdin

    - name: push to Tun Tun's Docker Hub
      run: |
        docker tag renter-score-api-v2:latest ***REMOVED***/dotnet-api:latest
        docker push ***REMOVED***/dotnet-api:latest
      working-directory: RenterScoreAPIv2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
  
    - name: Install Ansible
      run: pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook deploy-development.yml -i inventory \
        --extra-vars "connectionstring_default='${{ secrets.CONNECTIONSTRING_DEFAULT }}'"
      working-directory: Ansible      