name: Snyk

on:
  pull_request:
    branches: [ develop ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore .NET dependencies
        run: dotnet restore
      
      - name: Restore npm dependencies
        run: npm install
        working-directory: RenterScoreAPIv2.Test.EndToEnd

      - name: Install Snyk CLI
        run: npm install -g snyk snyk-to-html

      - name: Run Snyk to scan all projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --json > snyk-report.json | exit_code=$?
          echo "$exit_code"
          echo "SNYK_EXIT_CODE=$exit_code" >> $GITHUB_ENV
        continue-on-error: true
      
      - name: Generate Snyk report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk-report.json
            snyk-report.html

      - name: Exit with Snyk exit code
        run: exit $SNYK_EXIT_CODE
