name: Snyk

on:
  pull_request:
    branches: [ develop ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore .NET dependencies
        run: dotnet restore
      
      - name: Restore npm dependencies
        run: npm install
        working-directory: RenterScoreAPIv2.Test.EndToEnd

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for .NET projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=RenterScoreAPIv2.sln
      
      - name: Run Snyk to check for end-to-end tests
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=package.json
        working-directory: RenterScoreAPIv2.Test.EndToEnd
