name: Unit Test with Coverage

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Scan
      run: |
        dotnet build --no-restore --configuration Release 
        coverlet ./RenterScoreAPIv2.Test.Unit/bin/Release/net8.0/RenterScoreAPIv2.Test.Unit.dll \
          --target "dotnet" \
          --targetargs "test --no-build --configuration Release" \
          -f=opencover \
          -o="coverage.xml" \
          --threshold 55 \
          --threshold-type line \
          --threshold-stat total