name: Zap

on:
  workflow_run:
    workflows: ["Deploy - Development"]
    types:
      - completed

jobs:
  deploy-to-development-server: 
    runs-on: ubuntu-latest

    steps:    
    - name: Run ZAP API Scan
      continue-on-error: true
      run: |
        docker run --user root --network="host" \
        -v ${{ github.workspace }}:/zap/wrk/:rw \
        zaproxy/zap-stable zap-api-scan.py \
        -t http://***REMOVED***/swagger/v1/swagger.json \
        -f openapi \
        -r zap-report.html

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: ZAP Scan Report
        path: zap-report.html